- name: Copying over kvm_host this will be used to for the kvm variables
  template:
    src: templates/kvm_host.yml.j2
    dest:  /{{ inventory_dir }}/kvm_host.yml
    owner: admin
    group: admin
    mode: 0666