---
- name: Setup Satellite Post Installation
  hosts: qbn-sat01
  remote_user: root
  become: true
  gather_facts: true
  vars_files:
    - vars/all.yml
    - vars/kvm_host.yml
    - vars/vault.yml
    - vars/satellite_server.yml

  collections:
    - theforeman.foreman

  tasks:
  - name: TASK| runnning ansible-role-configure-katello
    include_role:
      name: redhat-satellite-quickstart
    tags: [always,manifest,org,location]
